#!/usr/bin/env bash
# Generated by Qwen3.6 running locally
set -euo pipefail

DEST_DIR="$HOME/.config/sublime-text/Packages/User"

# Ensure the destination directory exists
mkdir -p "$DEST_DIR"

# Link each .sublime-build file
for file in *.sublime-build; do
    [ -f "$file" ] || continue
    ln -sf "$(realpath "$file")" "$DEST_DIR/$file"
    echo "Linked $file -> $DEST_DIR/$file"
done
